# Generated by Django 5.2.1 on 2025-05-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product_remove_cart_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='promotions',
            field=models.ManyToManyField(blank=True, default=None, to='cart.promotion'),
        ),
    ]
