# Generated by Django 5.2.1 on 2025-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_product_category_alter_cart_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='cart.promotion'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default=None),
        ),
    ]
